### ISSUE TITLE
Ion Pumps use own pressure reading after turning on

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lcls-twincat-vacuum#20]
Ion Pumps should use their own pressure readings for validating setpoints and hysteresis after they have been turned on through the pressure of another gauge like an pirani gauge or a cold cathode.

**Comment by ghalym** [comment]
Should we also have them on auto on, i.e. when the interlocked gauge reads below the set point the ion pump should automatically start?
@slacAWallace

**Comment by slacAWallace** [comment]
I really really like this.
