### ISSUE TITLE
Gauges/Pumps that are interlocked should pass to EPICS the name of the interlocked component so they can be seen on the expert screens for debugging

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lcls-twincat-vacuum#21]
Gauges/Pumps that are interlocked should pass to EPICS the name of the interlocked component so they can be seen on the expert screens for debugging.

**Comment by ghalym** [comment]
I am not sure I understand. If a component is interlocked, the interlock state shows on the widget. Do you wanna show the reason why this device is interlocked?

**Comment by slacAdpai** [comment]
Yes, so the interlock state shows on the widget. In the expert screens, can we add what component that component is interlocked to?

**Comment by ghalym** [comment]
Its not always that straight forward. Most of the devices have an external interlock bit, that can be interlocked with any logical expression.  That applies to VGCs as well.
My initial thought was that there will be confluence page that shows the interlock table and interlock conditions for every device that is defined by the system's engineer.
For straight forward interlocks, I will see how to include that.

**Comment by slacAdpai** [comment]
After talking with Alex, he said that is would be a great idea to add clarity to the vacuum system for the user. Can we add another element in the structure to add the string name of the structure?

**Comment by ghalym** [comment]
What do you mean name of the structure?
