### ISSUE TITLE
Duplicate definition of variable 'fbLogger' in function block 'FB_PIP_Gamma' and in base 'FB_Pump' [lcls-twincat-vacuum, 0.0.0 (slac)]	FB_PIP_Gamma

### ISSUE THREAD

**Issue by klauer** [pcdshub/lcls-twincat-vacuum#25]
https://github.com/pcdshub/lcls-twincat-vacuum/blob/cae969c79ee5732afe7d2d9c32427fca54ff7acc/L2SIVacuum/POUs/Functions/Pumps/FB_PIP_Gamma.TcPOU#L30

https://github.com/pcdshub/lcls-twincat-vacuum/blob/cae969c79ee5732afe7d2d9c32427fca54ff7acc/L2SIVacuum/POUs/Functions/Pumps/FB_Pump.TcPOU#L12

**Comment by klauer** [comment]
Also: `Duplicate definition of variable 'tAction' in function block 'FB_PIP_Gamma' and in base 'FB_Pump' [lcls-twincat-vacuum, 0.0.0 (slac)]	FB_PIP_Gamma`

**Comment by klauer** [comment]
Hmm, `tAction` is `F_TRIG` in `FB_PIP_Gamma` but `R_TRIG` in `FB_Pump`

**Comment by ghalym** [comment]
Good Catch! Thanks!
I created a base class with all the logger variables, so that I won'to go on copy and paste in every pump function block. Forgot that it was in the pip already.
Still need more work to properly make it oo and modular.
