### ISSUE TITLE
FB_MKS500_EP shows as starting when out of range.

### ISSUE THREAD

**Issue by n-wbrown** [pcdshub/lcls-twincat-vacuum#27]
When the pressure on an MKS 500 drops sufficiently low, the function block considers gauge to be in a starting state and no longer reports the pressure.

In the image included you can see the green signal, the analog input to the PLC continuously decreasing. However, at certain point (https://github.com/pcdshub/lcls-twincat-vacuum/blob/cae969c79ee5732afe7d2d9c32427fca54ff7acc/L2SIVacuum/POUs/Functions/Gauges/FB_MKS500_EP.TcPOU#L49) the gauge is regarded as being in a `starting` STATE instead of `Valid`, `ValidLo`, `ValidHi`, or `OoR`. 

@slacAWallace I believe this is causing a few gauges in the FEE to appear to be starting despite having been running in a `Valid` state for at least a week. 

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/20483116/77483592-c51a6080-6de5-11ea-8464-44102117e4ee.png">
https://pswww.slac.stanford.edu/epicsarchiver/retrieval/ui/viewer/archViewer.html?pv=SP1K1:MONO:GCC:1:AT_VAC_RBV&pv=SP1K1:MONO:GCC:1:HV_ON_RBV&pv=SP1K1:MONO:GCC:1:PRESS_AI_RBV&pv=SP1K1:MONO:GCC:1:STATE_RBV&pv=SP1K1:MONO:GCC:1:PRESS_RBV&from=2020-03-17T22:34:41.249Z&to=2020-03-24T22:34:41.249Z

**Comment by ghalym** [comment]
@slacAWallace Do you remember why these values were put in? I remember asking that question before, but i don't remember the answer.
