### ISSUE TITLE
RS232 for FB_PTM_TurboDrive

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lcls-twincat-vacuum#30]
I cannot find the RS232 section for FB_PTM_TurboDrive. I am mainly interested in this interface for the TD20 classic.

**Comment by ghalym** [comment]
The RS232 implementations is part of another library 
https://github.com/pcdshub/lcls-twincat-vacuum-serialdrivers

**Comment by slacAdpai** [comment]
Thanks! I'll go check it out
