### ISSUE TITLE
MKS 500 Cold Cathode state is in error after starting

### ISSUE THREAD

**Issue by slacAdpai** [pcdshub/lcls-twincat-vacuum#33]
![image](https://user-images.githubusercontent.com/42284230/83988788-3489f180-a8f9-11ea-9400-72e47fd179c7.png)

**Comment by ghalym** [comment]
![TV1K4-GCC-1](https://user-images.githubusercontent.com/43865116/84041267-75fdb980-a958-11ea-9050-6700dcbd6b52.jpg)

It seems fine in the PLC and the pv is in error. I will double check the pragmas.
