### ISSUE TITLE
Malformed pragma

### ISSUE THREAD

**Issue by klauer** [pcdshub/lcls-twincat-vacuum#6]
https://github.com/pcdshub/L2SI-Vacuum-Lib/blob/fc443c9dac8acaed931a86cc1860c13056f58acb/L2SIVacuum/DUTs/Valves/ST_VCN.TcDUT#L16

**Comment by ghalym** [comment]
Nice catch! Thank you.
Fixing it right now.

**Comment by ghalym** [comment]
I also noticed that the STATE pragma was also malformed. Just pushed the fix.
